exclude: ^LICENSE/|\.(html|csv|svg|md|txt|json)$
default_stages: [commit]
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        entry: nbstripout
        language: python
        types: [jupyter]
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--settings-path=./pyproject.toml]
  - repo: https://github.com/python/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--target-version=py311]
        additional_dependencies: [".[jupyter]"]
        types_or: [python, jupyter]