FROM python:3.7.3

LABEL "com.github.actions.name"="PyPI Release"
LABEL "com.github.actions.description"="Upload to PyPI on GitHub release."
LABEL "com.github.actions.icon"="package"
LABEL "com.github.actions.color"="blue"

LABEL "repository"="https://github.com/FeatureLabs/compose-ml"
LABEL "maintainer"="support@featurelabs.com"

ENTRYPOINT [ "sh", "-c", "echo $HOME" ]
