on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Build Docs
jobs:
  doc_tests:
    name: Doc Tests / Python 3.8
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build source distribution
        run: make package
      - name: Install package with doc requirements
        run: |
          python -m pip config --site set global.progress_bar off
          python -m pip install unpacked_sdist/
          python -m pip install unpacked_sdist/[dev]
          python -m pip install unpacked_sdist/[docs]
          python -m pip check
          sudo apt install -q -y pandoc
          sudo apt install -q -y graphviz
      - name: Run doc tests
        run: make -C docs/ -e "SPHINXOPTS=-W" clean html
