on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Install Test
jobs:
  install_cm_complete:
    name: ${{ matrix.os }} - ${{ matrix.python_version }} install compose
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build compose package
        run: make package
      - name: Install compose complete from sdist
        run: |
          pip config --site set global.progress_bar off
          python -m pip install "unpacked_sdist/[complete]"
      - name: Test by importing packages
        run: |
          python -c "import alteryx_open_src_update_checker"
        env:
          ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
      - name: Check package conflicts
        run: |
          python -m pip check
