name: Unit Tests - Minimum Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  py36_unit_tests_minimum_dependencies:
    name: Unit Tests - 3.8 Minimum Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Set up python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build source distribution
        run: make package_build
      - name: Config pip, upgrade pip
        run: |
          python -m pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
          python -m pip install "$(cat composeml/tests/requirement_files/minimum_test_requirements.txt | grep wheel)"
      - name: Install composeml with no dependencies
        run: |
          python -m pip install -e . --no-dependencies
      - name: Install composeml - minimum tests requirements
        run: |
          python -m pip install -r composeml/tests/requirement_files/minimum_test_requirements.txt
      - name: Install composeml - minimum core requirements
        run: |
          python -m pip install -r composeml/tests/requirement_files/minimum_core_requirements.txt
      - name: Run unit tests (no code coverage)
        run: cd dist/package && make unit_tests -f ../../Makefile
